# Generated by Django 4.0.5 on 2022-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_category_blog_blog_img_blog_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='blogpost_imgs/'),
        ),
    ]
